import Head from "next/head";
import Cards from "../components/CardSection/Cards";
import InputHero from "../components/InputHero";
import CTA from "../components/CTA";
import { useRef, useEffect } from "react";

export default function Home() {

  useEffect(() => {
    const alanBtn = require('@alan-ai/alan-sdk-web');
    alanBtn({
      key: process.env.KEY,
      rootEl: document.getElementById("alan-btn"),
    });
  }, []);

  return (
    <div>
      <Head>
        <title>Medlabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InputHero />
      <div id="alan-btn" className="relative right-5" ></div>
      <Cards />
      <CTA />

      {/* <Testimonial /> */}
    </div>
  );
}
